ROOM_SAFE = "SAFE"
ROOM_WARNING = "WARNING"
ROOM_DANGEROUS = "DANGEROUS"
ROOM_CRITICAL = "CRITICAL"
ROOM_BLOCKED = "BLOCKED"

NODE_REAL = "REAL"
NODE_VIRTUAL = "VIRTUAL"

MQTT_PORT = 1883
MQTT_KEEPALIVE = 60